### ISSUE TITLE
Building on Arch Linux

### ISSUE THREAD

**Issue by xyproto** [mkeeter/futureproof#2]
Hi,

I'm trying to package futureproof for Arch Linux.

When I run `make wgpu shaderc` I get the following error:

```
cd wgpu && install_name_tool -id "@executable_path/../../vendor/wgpu/libwgpu_native.dylib" libwgpu_native.dylib
/bin/sh: line 1: install_name_tool: command not found
```

I'm testing with this `PKGBUILD` file:

```sh
pkgname=futureproof-git
pkgver=283.110948f
pkgrel=1
pkgdesc='Terminal emulator'
arch=(x86_64)
url='https://mattkeeter.com/projects/futureproof'
license=(MIT) # or Apache
conflicts=(futureproof)
depends=(freetype2 glfw)
makedepends=(git zig)
source=('git+https://github.com/mkeeter/futureproof')
sha256sums=(SKIP)

pkgver() {
  cd futureproof
  printf "%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

prepare() {
  cd futureproof/vendor
  make wgpu shaderc
}

build() {
  cd futureproof
  ZIG_SYSTEM_LINKER_HACK=1 zig build
}

package() {
  install -Dm755 futureproof/futureproof "$pkgdir/usr/bin/futureproof"
}
```

**Comment by mkeeter** [comment]
Unfortunately, `futureproof` is only supported on macOS right now – for example, that `Makefile` downloads macOS-specific libraries.  If you can get it working on Arch, then I'll accept a PR, but do not have the resources to support it myself.

**Comment by xyproto** [comment]
I missed that when quickly looking at the README. Thanks for the response.

I don't think macOS is a future proof choice, though, but that's just my opinion.
